### ISSUE TITLE
Example usage of "Rem font size conversion" shows px but should be ommitted

### ISSUE THREAD

**Issue by Jones-UI** [devcollaborative/drupal8-devcollab-lightship#4]
https://github.com/devcollaborative/drupal8-devcollab-lightship/blob/c7bee8b679f14d92f9950a34affa07575201e318/sass/base/_mixins.scss#L28

`@include fontSize(12px);`
should be:
`@include fontSize(12);`

**Comment by jbates** [comment]
Thank you! I just fixed that! Feel free to fix it in your BALS copy.
